import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Home, Users, Trophy, User } from "lucide-react"; // Importing icons
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-custom m-0 p-0`}>

        {/* 🔹 Main Content */}
        <main className="flex-1 w-full">{children}</main>

        {/* 🔹 Bottom Navigation Bar with Icons */}
        <nav className="fixed bottom-0 left-0 w-full bg-white dark:bg-gray-800 shadow-md p-4 flex justify-around border-t border-gray-300 dark:border-gray-700">
          <NavItem href="/" icon={<Home size={24} />} />
          <NavItem href="/Teams" icon={<Users size={24} />} />
          <NavItem href="/Leaderboard" icon={<Trophy size={24} />} />
          <NavItem href="/Profile" icon={<User size={24} />} />
        </nav>
        
      </body>
    </html>
  );
}

/* 🔹 Reusable Navigation Item Component */
const NavItem = ({ href, icon }: { href: string; icon: React.ReactNode }) => {
  return (
    <Link href={href} className="text-gray-600 dark:text-gray-300 hover:text-blue-500">
      {icon}
    </Link>
  );
};
