import type { Metadata } from 'next';
import Navbar from "../../components/Navbar";
import { Geist, Geist_Mono } from 'next/font/google';
import './styles/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Bouvet App',
  description: 'Generated by create next app',
  manifest: '/manifest.json', //Ensure manifest path is correct
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      <Navbar />
      </body>
    </html>
  );
}
